export const websites = [
  {
    id: 1,
    title: "Personal Website",
    fee: "One time fee for design",
    category: "Basic",
    support: "2 Months Website Support",
    domain: "Kshs. 4000 annual domain hosting fee",
    currency: "Kshs.",
    cost: "11,000",
    item1: "Up to 6 Website pages",
    item2: "Free Domain Name Hosting for 1 Year",
    item3: "3 Custom Emails",
    item4: "Social Media Integration with Chat button",
    item5: "Chat bot if needed",
    item6: "Website Security / SSL",
    item7: "Delivery within 7 Working Days",
    basic: true,
    websites: true,
    medium: false,
    premium: false,
    software: false,
    marketing: false,
    systems: false,
  },

  {
    id: 2,
    title: "Organization Website",
    fee: "One time fee for design",
    category: "Medium",
    support: "2 Months Website Support",
    domain: "Kshs. 4000 annual domain hosting fee",
    currency: "Kshs.",
    cost: "16,000",
    item1: "Up to 12 Website pages",
    item2: "Free Domain Name Hosting for 1 Year",
    item3: "6 Custom Emails + SEO Keyword Search",
    item4: "Social Media Integration with Chat button",
    item5: "Chat bot if needed",
    item6: "Website Security / SSL",
    item7: "Delivery within 10 Working Days",
    medium: true,
    websites: true,
    basic: false,
    premium: false,
    software: false,
    marketing: false,
    systems: false,
  },

  {
    id: 3,
    title: "E-Commerce Website",
    fee: "One time fee for design",
    category: "Value Pack",
    support: "2 Months Website Support",
    domain: "Kshs. 4000 annual domain hosting fee",
    currency: "Kshs.",
    cost: "50,000",
    item1: "Up to 25 Website pages",
    item2: "Free Domain Name Hosting for 1 Year",
    item3: "3 Custom Emails + SEO Web Content",
    item4: "Social Media Integration with Chat button",
    item5: "Chat bot + Analytic Dashboard + Payment Gateway",
    item6: "Website Security / SSL + Google Map Ranking",
    item7: "Delivery within 21 Working Days",
    premium: true,
    websites: true,
    basic: false,
    medium: false,
    software: false,
    marketing: false,
    systems: false,
  },
];

export const software = [
  {
    id: 1,
    title: "Chat Application",
    fee: "One time fee for design",
    category: "Premium",
    support: "2 Months Website Support",
    domain: "Kshs. 4000 annual domain hosting fee",
    currency: "Kshs.",
    cost: "33,000",
    item1: "Up to 6 Website pages",
    item2: "Free Domain Name Hosting for 1 Year",
    item3: "3 Custom Emails",
    item4: "Social Media Integration with Chat button",
    item5: "Chat bot if needed",
    item6: "Website Security / SSL",
    item7: "Delivery within 7 Working Days",
    basic: true,
    software: true,
    websites: false,
    medium: false,
    premium: false,
    marketing: false,
    systems: false,
  },

  {
    id: 2,
    title: "Mobile Applications",
    fee: "One time fee for design",
    category: "Medium",
    support: "2 Months Website Support",
    domain: "Kshs. 4000 annual domain hosting fee",
    currency: "Kshs.",
    cost: "46,000",
    item1: "Up to necessary number of pages",
    item2: "Free Domain Name Hosting for 1 Year",
    item3: "6 Custom Emails + SEO Keyword Search",
    item4: "Social Media Integration with Chat button",
    item5: "Chat bot if needed",
    item6: "Website Security / SSL",
    item7: "Delivery within 10 Working Days",
    premium: true,
    software: true,
    basic: false,
    websites: false,
    medium: false,
    marketing: false,
    systems: false,
  },

  {
    id: 3,
    title: "Any Kind Software",
    fee: "One time fee for design",
    category: "Value Pack",
    support: "2 Months Website Support",
    domain: "Kshs. 4000 annual domain hosting fee",
    currency: "",
    cost: "Negotiable",
    item1: "Up to necessary number of pages",
    item2: "Free Domain Name Hosting for 1 Year",
    item3: "3 Custom Emails + SEO Web Content",
    item4: "Social Media Integration with Chat button",
    item5: "Chat bot + Analytic Dashboard + Payment Gateway",
    item6: "Website Security / SSL + Google Map Ranking",
    item7: "Delivery within 21 Working Days",
    premium: true,
    software: true,
    basic: false,
    websites: false,
    medium: false,
    marketing: false,
    systems: false,
  },
];

export const systems = [
  {
    id: 1,
    title: "Employee Management System",
    fee: "One time fee for Development",
    category: "Value Pack",
    support: "2 Months Website Support",
    domain: "Kshs. 10000 annual domain hosting fee",
    currency: "Kshs.",
    cost: "11,000",
    item1: "Up to necessary number of pages",
    item2: "Free Domain Name Hosting for 1 Year",
    item3: "Up to necessary number of Emails",
    item4: "Social Media Integration with Chat button",
    item5: "AI enabled",
    item6: "Security / SSL",
    item7: "Delivery within 30 Working Days",
    premium: true,
    systems: true,
    basic: false,
    websites: false,
    medium: false,
    software: false,
    marketing: false,
  },

  {
    id: 2,
    title: "School Management System",
    fee: "One time fee for Development",
    category: "Value Pack",
    support: "2 Months Website Support",
    domain: "Kshs. 10000 annual domain hosting fee",
    currency: "Kshs.",
    cost: "16,000",
    item1: "Up to 12 Website pages",
    item2: "Free Domain Name Hosting for 1 Year",
    item3: "6 Custom Emails + SEO Keyword Search",
    item4: "Social Media Integration with Chat button",
    item5: "AI",
    item6: "Website Security / SSL",
    item7: "Delivery within 10 Working Days",
    premium: true,
    systems: true,
    basic: false,
    websites: false,
    medium: false,
    software: false,
    marketing: false,
  },

  {
    id: 3,
    title: "Any Kind of System",
    fee: "One time fee for Development",
    category: "Premium",
    support: "2 Months Website Support",
    domain: "Kshs. 15000 annual domain hosting fee",
    currency: "Kshs.",
    cost: "50,000",
    item1: "inclusive of Relevant Number of Pages",
    item2: "Free Domain Name Hosting for 1 Year",
    item3: "3 Custom Emails + SEO Web Content",
    item4: "Social Media Integration with Chat button",
    item5: "AI + Analytic Dashboard + Payment Gateway",
    item6: "Website Security / SSL + Google Map Ranking",
    item7: "Delivery within 21 Working Days",
    premium: true,
    systems: true,
    basic: false,
    websites: false,
    medium: false,
    software: false,
    marketing: false,
  },
];

export const marketing = [
  {
    id: 1,
    title: "Online Platforms",
    fee: "Monthly fee",
    category: "Basic",
    support: "2 Months Website Support",
    domain: "Kshs. 4000 annual domain hosting fee",
    currency: "Kshs.",
    cost: "16,000",
    item1: "Up to 6 Website pages",
    item2: "Free Domain Name Hosting for 1 Year",
    item3: "3 Custom Emails",
    item4: "Social Media Integration with Chat button",
    item5: "Chat bot if needed",
    item6: "Website Security / SSL",
    item7: "Delivery within 7 Working Days",
    basic: true,
    marketing: true,
    websites: false,
    medium: false,
    premium: false,
    software: false,
    systems: false,
  },

  {
    id: 2,
    title: "Complete SEO Control",
    fee: "Monthly Fee",
    category: "Value Pack",
    support: "2 Months Website Support",
    domain: "Kshs. 4000 annual domain hosting fee",
    currency: "Kshs.",
    cost: "26,000",
    item1: "Up to 12 Website pages",
    item2: "Free Domain Name Hosting for 1 Year",
    item3: "6 Custom Emails + SEO Keyword Search",
    item4: "Social Media Integration with Chat button",
    item5: "Chat bot if needed",
    item6: "Website Security / SSL",
    item7: "Delivery within 10 Working Days",
    medium: true,
    marketing: true,
    basic: false,
    websites: false,
    premium: false,
    software: false,
    systems: false,
  },

  {
    id: 3,
    title: "Digital Marketing Matrix",
    fee: "Monthly Fee",
    category: "Premium",
    support: "2 Months Website Support",
    domain: "Kshs. 4000 annual domain hosting fee",
    currency: "Kshs.",
    cost: "50,000",
    item1: "Up to 25 Website pages",
    item2: "Free Domain Name Hosting for 1 Year",
    item3: "3 Custom Emails + SEO Web Content",
    item4: "Social Media Integration with Chat button",
    item5: "Chat bot + Analytic Dashboard + Payment Gateway",
    item6: "Website Security / SSL + Google Map Ranking",
    item7: "Delivery within 21 Working Days",
    premium: true,
    marketing: true,
    basic: false,
    websites: false,
    medium: false,
    software: false,
    systems: false,
  },
];
